Count,Message,Traceback,Nodes
320891,Invalid URL 'http:///api/user/login': No host supplied,"  File ""/home/krish/.local/lib/python3.8/site-packages/locust/user/task.py"", line 296, in run
    self.execute_next_task()
  File ""/home/krish/.local/lib/python3.8/site-packages/locust/user/task.py"", line 321, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/home/krish/.local/lib/python3.8/site-packages/locust/user/task.py"", line 434, in execute_task
    task(self.user)
  File ""/home/krish/Desktop/Level 4 Project Files /Fruit-Cocktail/src/Part_1/lime/temp_load/locustfile.py"", line 41, in login
    res = self.client.post('/api/user/login', json=credentials, headers={'x-forwarded-for': fake_ip})
  File ""/home/krish/.local/lib/python3.8/site-packages/requests/sessions.py"", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File ""/home/krish/.local/lib/python3.8/site-packages/locust/clients.py"", line 129, in request
    response = self._send_request_safe_mode(method, url, **kwargs)
  File ""/home/krish/.local/lib/python3.8/site-packages/locust/clients.py"", line 197, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
  File ""/home/krish/.local/lib/python3.8/site-packages/requests/sessions.py"", line 528, in request
    prep = self.prepare_request(req)
  File ""/home/krish/.local/lib/python3.8/site-packages/requests/sessions.py"", line 456, in prepare_request
    p.prepare(
  File ""/home/krish/.local/lib/python3.8/site-packages/requests/models.py"", line 316, in prepare
    self.prepare_url(url, params)
  File ""/home/krish/.local/lib/python3.8/site-packages/requests/models.py"", line 393, in prepare_url
    raise InvalidURL(""Invalid URL %r: No host supplied"" % url)
",local
321209,Invalid URL 'http:///': No host supplied,"  File ""/home/krish/.local/lib/python3.8/site-packages/locust/user/task.py"", line 296, in run
    self.execute_next_task()
  File ""/home/krish/.local/lib/python3.8/site-packages/locust/user/task.py"", line 321, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/home/krish/.local/lib/python3.8/site-packages/locust/user/task.py"", line 434, in execute_task
    task(self.user)
  File ""/home/krish/Desktop/Level 4 Project Files /Fruit-Cocktail/src/Part_1/lime/temp_load/locustfile.py"", line 49, in load
    self.client.get('/', headers={'x-forwarded-for': fake_ip})
  File ""/home/krish/.local/lib/python3.8/site-packages/requests/sessions.py"", line 555, in get
    return self.request('GET', url, **kwargs)
  File ""/home/krish/.local/lib/python3.8/site-packages/locust/clients.py"", line 129, in request
    response = self._send_request_safe_mode(method, url, **kwargs)
  File ""/home/krish/.local/lib/python3.8/site-packages/locust/clients.py"", line 197, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
  File ""/home/krish/.local/lib/python3.8/site-packages/requests/sessions.py"", line 528, in request
    prep = self.prepare_request(req)
  File ""/home/krish/.local/lib/python3.8/site-packages/requests/sessions.py"", line 456, in prepare_request
    p.prepare(
  File ""/home/krish/.local/lib/python3.8/site-packages/requests/models.py"", line 316, in prepare
    self.prepare_url(url, params)
  File ""/home/krish/.local/lib/python3.8/site-packages/requests/models.py"", line 393, in prepare_url
    raise InvalidURL(""Invalid URL %r: No host supplied"" % url)
",local
